import { Board, CellCoord, Tile, cellKey, edgeNeighbors, emptyBoard, placeTile } from '@triominos/shared';

export interface PuzzlePoint {
  cell: CellCoord;
  values: [number, number, number];
}

export interface PuzzleLevel {
  id: string;
  name: string;
  /** The two fixed anchor tiles the player must connect. */
  pointA: PuzzlePoint;
  pointB: PuzzlePoint;
  /** The exact tiles handed to the player -- enough to connect the points, no spares. */
  tiles: Tile[];
}

/**
 * Each level was generated by literally playing a random legal chain out with the real
 * board engine (findLegalPlacements/placeTile), then taking its two ends as the points and
 * everything in between as the hand -- so a solution using every given tile is always
 * guaranteed to exist, and rejected if the two points already touched before any tile was
 * placed (which would make the puzzle trivial).
 */
export const PUZZLE_LEVELS: PuzzleLevel[] = [
  {
    id: 'level-1',
    name: 'Puzzle 1',
    pointA: { cell: { q: 0, r: 0, orient: 'up' }, values: [3, 3, 5] },
    pointB: { cell: { q: -2, r: 0, orient: 'up' }, values: [3, 1, 2] },
    tiles: [
      { id: '1-3-5', values: [1, 3, 5] },
      { id: '1-1-3', values: [1, 1, 3] },
      { id: '1-1-2', values: [1, 1, 2] },
    ],
  },
  {
    id: 'level-2',
    name: 'Puzzle 2',
    pointA: { cell: { q: 0, r: 0, orient: 'up' }, values: [3, 5, 5] },
    pointB: { cell: { q: 2, r: -3, orient: 'down' }, values: [1, 0, 1] },
    tiles: [
      { id: '3-4-5', values: [3, 4, 5] },
      { id: '4-4-5', values: [4, 4, 5] },
      { id: '0-4-4', values: [0, 4, 4] },
      { id: '0-1-4', values: [0, 1, 4] },
    ],
  },
  {
    id: 'level-3',
    name: 'Puzzle 3',
    pointA: { cell: { q: 0, r: 0, orient: 'up' }, values: [1, 1, 3] },
    pointB: { cell: { q: 3, r: -2, orient: 'up' }, values: [3, 3, 0] },
    tiles: [
      { id: '1-1-5', values: [1, 1, 5] },
      { id: '0-1-5', values: [0, 1, 5] },
      { id: '0-0-1', values: [0, 0, 1] },
      { id: '0-0-0', values: [0, 0, 0] },
      { id: '0-0-3', values: [0, 0, 3] },
    ],
  },
  {
    id: 'level-4',
    name: 'Puzzle 4',
    pointA: { cell: { q: 0, r: 0, orient: 'up' }, values: [2, 4, 5] },
    pointB: { cell: { q: 0, r: -3, orient: 'down' }, values: [0, 5, 5] },
    tiles: [
      { id: '2-2-4', values: [2, 2, 4] },
      { id: '1-2-2', values: [1, 2, 2] },
      { id: '1-1-2', values: [1, 1, 2] },
      { id: '1-1-4', values: [1, 1, 4] },
      { id: '1-4-5', values: [1, 4, 5] },
      { id: '1-5-5', values: [1, 5, 5] },
    ],
  },
  {
    id: 'level-5',
    name: 'Puzzle 5',
    pointA: { cell: { q: 0, r: 0, orient: 'up' }, values: [0, 1, 3] },
    pointB: { cell: { q: -1, r: 4, orient: 'up' }, values: [5, 5, 5] },
    tiles: [
      { id: '1-1-3', values: [1, 1, 3] },
      { id: '1-2-3', values: [1, 2, 3] },
      { id: '1-2-2', values: [1, 2, 2] },
      { id: '2-2-4', values: [2, 2, 4] },
      { id: '0-2-4', values: [0, 2, 4] },
      { id: '0-4-5', values: [0, 4, 5] },
      { id: '4-5-5', values: [4, 5, 5] },
    ],
  },
];

export const POINT_A_TILE_ID = 'point-a';
export const POINT_B_TILE_ID = 'point-b';

/** A fresh board holding just the level's two anchor tiles, nothing else. */
export function initialPuzzleBoard(level: PuzzleLevel): Board {
  let board = emptyBoard();
  board = placeTile(board, POINT_A_TILE_ID, level.pointA.cell, level.pointA.values);
  board = placeTile(board, POINT_B_TILE_ID, level.pointB.cell, level.pointB.values);
  return board;
}

/** True once the two points sit in the same edge-connected group of placed tiles. */
export function isPuzzleSolved(board: Board, level: PuzzleLevel): boolean {
  const startKey = cellKey(level.pointA.cell);
  const goalKey = cellKey(level.pointB.cell);
  if (!board[startKey] || !board[goalKey]) return false;
  if (startKey === goalKey) return true;

  const seen = new Set([startKey]);
  const queue: CellCoord[] = [level.pointA.cell];
  while (queue.length > 0) {
    const cur = queue.shift()!;
    for (const neighbor of edgeNeighbors(cur)) {
      const key = cellKey(neighbor);
      if (key === goalKey) return true;
      if (board[key] && !seen.has(key)) {
        seen.add(key);
        queue.push(neighbor);
      }
    }
  }
  return false;
}

const PROGRESS_KEY = 'triominos:puzzleprogress';

/** Set of level ids the player has solved at least once. */
export function loadPuzzleProgress(): Set<string> {
  try {
    const raw = localStorage.getItem(PROGRESS_KEY);
    if (!raw) return new Set();
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? new Set(parsed.filter((id) => typeof id === 'string')) : new Set();
  } catch {
    return new Set();
  }
}

export function markPuzzleSolved(levelId: string): Set<string> {
  const solved = loadPuzzleProgress();
  solved.add(levelId);
  try {
    localStorage.setItem(PROGRESS_KEY, JSON.stringify([...solved]));
  } catch {
    // Storage can be unavailable (private mode); progress just won't persist.
  }
  return solved;
}
